services:
  rustfs:
    profiles:
      - dev
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_VOLUMES=/data/rustfs
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_ACCESS_KEY=${S3_ACCESS_KEY_ID}
      - RUSTFS_SECRET_KEY=${S3_SECRET_ACCESS_KEY}
    volumes:
      - rustfs:/data
    networks:
      - rustfs
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://127.0.0.1:9000/health"]
      interval: 10s
      retries: 5
    restart: unless-stopped

  rustfs-init:
    profiles:
      - dev
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    networks:
      - rustfs
    depends_on:
      rustfs:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set rustfs http://rustfs:9000 $S3_ACCESS_KEY_ID $S3_SECRET_ACCESS_KEY;
      /usr/bin/mc mb --ignore-existing rustfs/${S3_BUCKET};
      "
    restart: no

  postgres:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${PSQL_ROOT_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      retries: 5
    restart: unless-stopped

  ollama:
    image: ollama/ollama:0.12.3
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "ollama", "ls"]
      interval: 10s
      retries: 3
    restart: unless-stopped

  ollama-init:
    image: alpine/curl:8.14.1
    networks:
      - ollama
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      MODELS: ${OLLAMA_MODELS}
    entrypoint: |
      /bin/sh -c '
      IFS=,; set -- $${MODELS};
      for model in "$$@"; do
        echo "==> Downloading model: $$model"
        curl -X POST http://ollama:11434/api/pull \
          -H "Content-Type: application/json" \
          -d "{\"name\": \"$$model\"}"
      done
      '
    restart: no

  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.6.32
    ports:
      - "8080:8080"
    environment:
      OLLAMA_BASE_URL: http://ollama:11434/
    volumes:
      - open-webui:/app/backend/data
    networks:
      - ollama
    depends_on:
      - ollama
    restart: unless-stopped

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - mlflow:/mlflow
    networks:
      - mlflow
      - rustfs
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://rustfs:9000
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${S3_REGION}
      AWS_S3_ADDRESSING_STYLE: ${S3_URL_STYLE}
    command: >
      mlflow server
        --backend-store-uri sqlite:///mlflow/mlflow.db
        --serve-artifacts
        --artifacts-destination s3://${S3_MLFLOW_BUCKET}/${S3_MLFLOW_ARTIFACTS_PREFIX}
        --host 0.0.0.0
        --port 5000
    healthcheck:
      test: >
        python -c "import urllib.request;
        urllib.request.urlopen('http://localhost:5000')"
      interval: 10s
      retries: 5
    restart: unless-stopped

  kafka:
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://${KAFKA_BROKER_ENDPOINT},INTERNAL://kafka:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka:/var/lib/kafka/data
    networks:
      - kafka
    healthcheck:
      test: [
        "CMD", "bash", "-c",
        "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --list"
      ]
      interval: 10s
      retries: 5
    restart: unless-stopped

  kafka-init:
    image: apache/kafka:4.0.0
    environment:
      KAFKA_GROUP_TOPIC_LIST: ${KAFKA_GROUP_TOPIC_LIST}
    networks:
      - kafka
    depends_on:
      kafka:
        condition: service_healthy
    command: |
        /bin/bash -c '
        for topic_group in $${KAFKA_GROUP_TOPIC_LIST//,/ }; do
          IFS=':' read -r topic group <<< "$$topic_group"

          echo "Creating topic: $$topic"
          /opt/kafka/bin/kafka-topics.sh \
            --bootstrap-server kafka:29092 \
            --create --if-not-exists --topic $$topic \
            --partitions 1 --replication-factor 1

          echo "Initializing consumer for topic $$topic and group $$group"
          /opt/kafka/bin/kafka-console-consumer.sh \
            --bootstrap-server kafka:29092 \
            --topic $$topic \
            --group $$group \
            --timeout-ms 5000
        done
        '
    restart: no

  portainer:
    image: portainer/portainer-ce:2.33.2
    ports:
      - 9080:9000
    volumes:
      - portainer:/data
    networks:
      - portainer
    restart: unless-stopped

volumes:
  rustfs:
  postgres:
  ollama:
  open-webui:
  mlflow:
  kafka:
  portainer:

networks:
  postgres:
  ollama:
  rustfs:
  mlflow:
  kafka:
  portainer:
